# -*- coding: utf-8 -*-
"""pascals.triangle.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jEoIChuMGDRkh2hNjWJA8rh0xixGUUcr
"""

def generate_pascals_triangle(n):
    triangle = []
    for i in range(n):
        row = [1] * (i + 1)
        if i >= 2:
            for j in range(1, i):
                row[j] = triangle[i - 1][j - 1] + triangle[i - 1][j]
        triangle.append(row)
    for row in triangle:
        print(' '.join(map(str, row)))

n = int(input())
generate_pascals_triangle(n)