# -*- coding: utf-8 -*-
"""tamrin4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ORjODwSWSmqIERR2SmOuTzdHh4WH2Bap
"""

def create_maze(n, moves):
    maze = [['.' for _ in range(n)] for _ in range(n)]
    x, y = 0, 0
    for move in moves:
        if move == 'R':
            y += 1
        elif move == 'L':
            y -= 1
        elif move == 'B':
            x += 1
        if x < 0 or x >= n or y < 0 or y >= n:
            print_maze(maze)
            print("There’s no way out!")
            return
        maze[x][y] = '*'
    print_maze(maze)

def print_maze(maze):
    for row in maze:
        print(' '.join(row))

n = int(input("Enter the number of columns (n): "))
moves = []
while True:
    move = input("Enter the next move (R/L/B) or END to finish: ")
    if move == "END":
        break
    moves.append(move)

create_maze(n, moves)